apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: netiedge
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/doganyazar/edge-krew/releases/download/v0.1.0/netiedge_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./netiedge"
      to: "."
    - from: LICENSE
      to: "."
    bin: "netiedge"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/doganyazar/edge-krew/releases/download/v0.1.0/netiedge_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./netiedge"
      to: "."
    - from: LICENSE
      to: "."
    bin: "netiedge"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/doganyazar/edge-krew/releases/download/v0.1.0/netiedge_windows_amd64.zip
    sha256: ""
    files:
    - from: "/netiedge.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "netiedge.exe"
  shortDescription: A new plugin
  homepage: https://github.com/doganyazar/edge-krew
  caveats: |
    Usage:
      $ kubectl netiedge

    For additional options:
      $ kubectl netiedge --help
      or https://github.com/doganyazar/edge-krew/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
